version: '2'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
  back:
    build: ./back
    depends_on:
      - mongo
    env_file:
      - ./env/dev.env
    ports:
      - 4000:4000
    volumes:
      - ./back/node_modules:/app/node_modules:rw
      - ./back/package.json:/app/package.json:rw
      - ./back/.eslintrc/json:/app/.eslintrc/json:rw
      - ./back/public:/app/public:rw
      - ./back/src:/app/src:rw
  front:
    build: ./front
    env_file:
      - ./env/dev.env
    ports:
      - 3000:3000
    # restart: always
    volumes:
      - ./front/node_modules:/app/node_modules:rw
      - ./front/package.json:/app/package.json:rw
      - ./front/package-lock.json:/app/package-lock.json:rw
      - ./front/public:/app/public:rw
      - ./front/src:/app/src:rw
  # server:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./dist:/usr/share/nginx/html/dist
  #     - ./server/error-pages:/usr/share/nginx/html/error
  #     - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
  